export const entityTypes: string[] = [
	"ADF",
	"CCN",
	"CGA",
	"CGE",
	"CMT",
	"COP",
	"CSS",
	"CTD",
	"CUT",
	"DES",
	"DIT",
	"DST",
	"DTT",
	"FPT",
	"FUT",
	"FXT",
	"HYT",
	"LGE",
	"LPT",
	"LSS",
	"NPF",
	"NRF",
	"OIE",
	"PDF",
	"POF",
	"PQT",
	"PRV",
	"PST",
	"PTR",
	"PTT",
	"PUB",
	"PUT",
	"SAF",
	"SCN",
	"SCO",
	"SCR",
	"SGA",
	"SGE",
	"SGT",
	"SMF",
	"SSS",
	"STI",
	"STR",
	"STU",
	"SUP",
	"TGA",
	"TGE",
	"TRT",
	"TTF",
	"TTI",
	"UIE",
];

export const entityTypeDescriptions: { [key: string]: string } = {
	ADF: "Approved Deposit Fund",
	CCN: "Co-operative Company",
	CGA: "Corporate Commonwealth Government Agency",
	CGE: "Corporate Commonwealth Government Entity",
	CMT: "Corporate Unit Trust",
	COP: "Co-operative",
	CSS: "Commonwealth Superannuation Scheme",
	CTD: "Corporate Trading Trust",
	CUT: "Corporate Unit Trust",
	DES: "Discretionary Estate Settlement",
	DIT: "Discretionary Investment Trust",
	DST: "Discretionary Services Trust",
	DTT: "Discretionary Trading Trust",
	FPT: "Fixed Unit Trust",
	FUT: "Fixed Unit Trust",
	FXT: "Fixed Unit Trust",
	HYT: "Hybrid Trust",
	LGE: "Local Government Entity",
	LPT: "Listed Public Company",
	LSS: "Large Scale Generation Certificate",
	NPF: "Not for Profit Company",
	NRF: "Natural Resource Fund",
	OIE: "Other Incorporated Entity",
	PDF: "Pooled Development Fund",
	POF: "Pooled Investment Fund",
	PQT: "Public Unit Trust",
	PRV: "Private Company",
	PST: "Public Company",
	PTR: "Partnership",
	PTT: "Public Trading Trust",
	PUB: "Public Company",
	PUT: "Public Unit Trust",
	SAF: "Small APRA Fund",
	SCN: "Strata Community",
	SCO: "Strata Company",
	SCR: "Strata Corporation",
	SGA: "State Government Agency",
	SGE: "State Government Entity",
	SGT: "Strata Trust",
	SMF: "Self Managed Super Fund",
	SSS: "State Superannuation Scheme",
	STI: "Strata Investment",
	STR: "Strata",
	STU: "Student Union",
	SUP: "Superannuation Fund",
	TGA: "Territory Government Agency",
	TGE: "Territory Government Entity",
	TRT: "Trust",
	TTF: "Testamentary Trust Fund",
	TTI: "Testamentary Trust Investment",
	UIE: "Unincorporated Entity",
};

export const gstStatuses: string[] = ["Active", "Inactive"];
export const states: string[] = [
	"NSW",
	"VIC",
	"QLD",
	"WA",
	"SA",
	"TAS",
	"ACT",
	"NT",
];
export const popularEntityTypes: string[] = [
	"PRV",
	"PUB",
	"PTR",
	"TRT",
	"SMF",
	"NPF",
];
export const sortOptions = [
	{ value: "entity_name", label: "Company Name" },
	{ value: "abn", label: "ABN" },
	{ value: "registration_date", label: "Registration Date" },
];

export const ignoreWords = ["PTY", "LTD", "INC", "LLC", "CO", "CORP", "THE"];
export const GRADIENT_COLORS = [
	"from-blue-500 to-indigo-600",
	"from-emerald-500 to-teal-600",
	"from-purple-500 to-pink-600",
	"from-orange-500 to-red-600",
	"from-cyan-500 to-blue-600",
] as const;

export const ANIMATION_DURATION = {
	fast: "duration-200",
	medium: "duration-300",
	slow: "duration-500",
	extra_slow: "duration-1000",
} as const;
